### ISSUE TITLE
db_users.db

### ISSUE THREAD

**Issue by 6--** [DVolodyslavD/QR-coder_bot#1]
Hello,

Kindly upload your "db_users.db" example, with some random names and numbers.

The bot wont generate one and it will give much errors.

```
[2021-06-18 05:30:41,608](INFO): "executor.py", line:362, _welcome - Bot:  [@]
[2021-06-18 05:30:41,608](INFO): "dispatcher.py", line:360, start_polling - Start polling.
[2021-06-18 05:30:47,935](ERROR): "base_events.py", line:1738, default_exception_handler - Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at C:\p3\lib\site-packages\aiogram\dispatcher\dispatcher.py:409> exception=DatabaseError('file is not a database')>
Traceback (most recent call last):
  File "C:\p3\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\p3\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\p3\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\p3\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\p3\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\Administrator\Desktop\QR-coder_bot-main\bot.py", line 15, in start_command
    result = select_users(DB_FILE)
  File "C:\Users\Administrator\Desktop\QR-coder_bot-main\sq_statement.py", line 8, in select_users
    cur.execute("SELECT user_id FROM all_users")
sqlite3.DatabaseError: file is not a database

```

Thanks

**Comment by DVolodyslavD** [comment]
I added a database file.

**Comment by 6--** [comment]
it's working now!

Thank you a lot!

Lovely code!
